@startuml Model1
skinparam classAttributeIconSize 0

User o-- Building
Building *-- Adress
City o-- Building
Building *-- Category
Building o-- Spec
Spec *-- Type

class User{
    - int idUser
    - String email
    - String passWord
    - int role
    - List<Building> Buildings
    + String getIdUser()
    + void setIdUser(int id)
    + String getEmail()
    + void setEmail(String email)
    + String getPassWord()
    + void setPassWord(String email)
    + String getRole()
    + void setRole(int id)
    + List<Building> getBuildings()
    + void addBuilding(Building building);
    + void removeBuilding(Building building);
}

class City{
    - int idCity
    - String name
    - List<Building> Buildings
    + String getIdCity()
    + void setIdCity(int id)
    + String getName()
    + void setName(String name)
    + List<Building> getBuildings()
    + void addBuilding(Building building);
    + void removeBuilding(Building building);
}

class Building{
    -int idBuilding
    -String name
    -Adress adress
    -List<String> photos
    -String description
    -Category category
    -int constructionYear
    -String architect
    -List<Spec> Specs
    + int getIdBuilding()
    + void setIdBuilding(int id)
    + String getName()
    + void setName(String name)
    + Adress getAdress()
    + void setAdress(Adress adress)
    + List<String> getBuildings()
    + void addBuilding(String photo);
    + void removeBuilding(String photo);
    + String getDescription()
    + void setDescription(String description)
    + String getCategory()
    + void setCategory(Category category)
    + int getConstructionYear()
    + void setConstructionYear(int constructionYear)
    + String getArchitect()
    + void setArchitect(String architect)
    + List<Spec> getSpecs()
    + void addSpecs(Spec spec);
    + void removeSpecs(Spec spec);
}

class Adress{
    - int idAdress
    - int number
    - String streetName
    - int zipCode
    - String city
    - Point coordinate
    + int getIdAdress()
    + void setIdAdress(int id)
    + String getNumber()
    + void setNumber(int number)
    + String getStreetName()
    + void setStreetName(String name)
    + String getZipCode()
    + void setZipCode(int zipCode)
    + String getCity()
    + void setCity(String city)
    + Point getCoordinate()
    + void setCoordinate(Point coordinate)
}

enum Category{
    null
    Castle
    House
    Building
    Ruin
}

class Spec{
    -int idSpec
    -Type name
    -String description
    -List<String> photos
    + int getidSpec()
    + void setidSpec(int id)
    + String getName()
    + void setName(String name)
    + String getDescription()
    + void setDescription(String description)

}

enum Type{
    Fundation
    Windows
    Roof
    Wall
}

@enduml

@startuml model Mod

actor User 
User -> ApiLogin : Login et MPD
ApiLogin -> User : OK
User -> ApiCity : get all
database H2DB
ApiCity -> H2DB
H2DB -> ApiCity
ApiCity -> User : List<city>
User -> ApiBuilding : getbuilding From City
ApiBuilding -> H2DB
H2DB -> ApiBuilding
ApiBuilding -> User :List<Building>
User -> User : choisir ses batiments
User -> ApiMap : envoie sa liste
ApiMap -> OpenStreetMap
OpenStreetMap -> ApiMap
ApiMap -> User : renvoi une image ?

@enduml