INSERT INTO building_city VALUES (1,'Cathédrale Notre-Dame','https://en.wikipedia.org/wiki/File:Strasbourg_Cathedral_Exterior_-_Diliff.jpg');
INSERT INTO building_city VALUES (2,'Barrage Vauban','https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Ponts_Couverts_Strasbourg_FRA_001.JPG/1920px-Ponts_Couverts_Strasbourg_FRA_001.JPG');
INSERT INTO building_city VALUES (3,'Maison des Tanneurs','https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Stra%C3%9Fburg_-_panoramio.jpg/1280px-Stra%C3%9Fburg_-_panoramio.jpg');
INSERT INTO building_city VALUES (4,'Pixel Museum','https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Pixel_Museum_%2825%29.jpg/1200px-Pixel_Museum_%2825%29.jpg');
INSERT INTO building_city VALUES (5,'Tour Eiffel','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Jielbeaumadier_tour_eiffel_paris_2007.jpg/1280px-Jielbeaumadier_tour_eiffel_paris_2007.jpg');
INSERT INTO building_city VALUES (6,'Musée du Louvre','https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Louvre_Museum_Wikimedia_Commons.jpg/1920px-Louvre_Museum_Wikimedia_Commons.jpg');
INSERT INTO building_city VALUES (7,'Arc de Triomphe','https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Arc_de_Triomphe%2C_Paris_21_October_2010.jpg/1280px-Arc_de_Triomphe%2C_Paris_21_October_2010.jpg');
INSERT INTO building_city VALUES (8,'Place Bellecour','https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Bellecour_-_H%C3%B4tel_Dieu%2C_Lyon%2C_France_-_panoramio_%284%29.jpg/1920px-Bellecour_-_H%C3%B4tel_Dieu%2C_Lyon%2C_France_-_panoramio_%284%29.jpg');
INSERT INTO building_city VALUES (9,'La Basilique Notre Dame de Fourvière','https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Notre_Dame_de_Fourvi%C3%A8re.jpg/1920px-Notre_Dame_de_Fourvi%C3%A8re.jpg');
INSERT INTO city VALUES (1,'Strasbourg');
INSERT INTO city VALUES (2,'Paris');
INSERT INTO city VALUES (3,'Lyon');
INSERT INTO city_buildings VALUES (1,1);
INSERT INTO city_buildings VALUES (1,2);
INSERT INTO city_buildings VALUES (1,3);
INSERT INTO city_buildings VALUES (1,4);
INSERT INTO city_buildings VALUES (2,5);
INSERT INTO city_buildings VALUES (2,6);
INSERT INTO city_buildings VALUES (2,7);
INSERT INTO city_buildings VALUES (3,8);
INSERT INTO city_buildings VALUES (3,9);
